# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currentMonth', models.TextField(default='')),
                ('currentRate', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('makerName', models.TextField(default='')),
                ('makerPhoto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modelName', models.TextField(default='')),
                ('modelPhoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('factoryPrice', models.IntegerField(default=0)),
                ('maker', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='answer.Maker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
