# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('userKey', models.TextField(default='')),
                ('modelChoice', models.BooleanField(default=False)),
                ('phoneModel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='answer.PhoneModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
